# Generated by Django 6.0.4 on 2026-05-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_add_990_index_parse_phases'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilingIndex',
            fields=[
                ('object_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ein', models.CharField(max_length=9)),
                ('tax_period', models.CharField(max_length=6)),
                ('return_type', models.CharField(max_length=10)),
                ('sub_date', models.CharField(max_length=20, null=True)),
                ('return_ts', models.DateTimeField(null=True)),
                ('is_amended', models.BooleanField(default=False)),
                ('taxpayer_name', models.TextField(null=True)),
                ('xml_batch_id', models.CharField(max_length=30, null=True)),
                ('filing_year', models.IntegerField()),
                ('status', models.CharField(choices=[('indexed', 'Indexed'), ('downloaded', 'Downloaded'), ('parsed', 'Parsed'), ('error', 'Error'), ('batch_unresolvable', 'Batch Unresolvable'), ('skipped', 'Skipped')], max_length=20)),
                ('error_message', models.TextField(null=True)),
                ('parsed_at', models.DateTimeField(null=True)),
                ('run_id', models.CharField(max_length=50, null=True)),
                ('first_indexed_at', models.DateTimeField(null=True)),
                ('last_seen_at', models.DateTimeField(null=True)),
                ('s3_xml_key', models.TextField(null=True)),
                ('zip_checksum', models.TextField(null=True)),
            ],
            options={
                'db_table': 'filing_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndexRefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_year', models.IntegerField()),
                ('refreshed_at', models.DateTimeField()),
                ('rows_scanned', models.IntegerField(default=0)),
                ('rows_inserted', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('duration_sec', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'index_refresh_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ein', models.CharField(max_length=9)),
                ('tax_period', models.CharField(max_length=6)),
                ('object_id', models.CharField(max_length=30)),
                ('person_name', models.CharField(max_length=200)),
                ('title', models.TextField(null=True)),
                ('person_type', models.CharField(max_length=30)),
                ('avg_hours_per_week', models.DecimalField(decimal_places=1, max_digits=5, null=True)),
                ('reportable_comp', models.BigIntegerField(null=True)),
                ('related_org_comp', models.BigIntegerField(null=True)),
                ('other_comp', models.BigIntegerField(null=True)),
                ('total_comp', models.BigIntegerField(null=True)),
                ('base_comp', models.BigIntegerField(null=True)),
                ('bonus', models.BigIntegerField(null=True)),
                ('other_reportable', models.BigIntegerField(null=True)),
                ('deferred_comp', models.BigIntegerField(null=True)),
                ('nontaxable_benefits', models.BigIntegerField(null=True)),
                ('total_comp_sch_j', models.BigIntegerField(null=True)),
                ('services_desc', models.TextField(null=True)),
                ('is_officer', models.BooleanField(default=False)),
                ('is_director', models.BooleanField(default=False)),
                ('is_key_employee', models.BooleanField(default=False)),
                ('is_highest_comp', models.BooleanField(default=False)),
                ('is_former', models.BooleanField(default=False)),
                ('extracted_at', models.DateTimeField(null=True)),
                ('run_id', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('stale', 'Stale')], default='offline', max_length=20)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'workers',
            },
        ),
        migrations.AlterField(
            model_name='job',
            name='phase',
            field=models.CharField(choices=[('seed', 'Seed'), ('resolve', 'Resolve'), ('crawl', 'Crawl'), ('classify', 'Classify'), ('990-enrich', '990 Enrich'), ('990-index', '990 Index'), ('990-parse', '990 Parse'), ('enrich-phone', 'Phone Enrich')], max_length=20),
        ),
    ]
