# Generated by Django 6.0.4 on 2026-05-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_filingindex_indexrefreshlog_person_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='log_tail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
