# Generated by Django 6.0.4 on 2026-05-14 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_job_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgProvenance',
            fields=[
                ('ein', models.TextField(primary_key=True, serialize=False)),
                ('seed_status', models.TextField(default='not_started')),
                ('seed_completed_at', models.DateTimeField(blank=True, null=True)),
                ('resolve_status', models.TextField(default='not_started')),
                ('resolve_completed_at', models.DateTimeField(blank=True, null=True)),
                ('crawl_status', models.TextField(default='not_started')),
                ('crawl_completed_at', models.DateTimeField(blank=True, null=True)),
                ('classify_status', models.TextField(default='not_started')),
                ('classify_completed_at', models.DateTimeField(blank=True, null=True)),
                ('filing_990_status', models.TextField(default='not_started')),
                ('filing_990_completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"lava_pipeline"."org_provenance"',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HostCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('command', models.CharField(choices=[('start-orchestrator', 'Start Orchestrator'), ('stop-orchestrator', 'Stop Orchestrator'), ('restart-orchestrator', 'Restart Orchestrator'), ('start-dashboard', 'Start Dashboard'), ('stop-dashboard', 'Stop Dashboard'), ('restart-dashboard', 'Restart Dashboard'), ('report-status', 'Report Status'), ('cleanup-locks', 'Cleanup Locks'), ('kill-process', 'Kill Process')], max_length=50)),
                ('args_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'host_commands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('paused_by', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'pipeline_config',
            },
        ),
        migrations.RenameIndex(
            model_name='jobevent',
            new_name='job_events_job_id_9d17d5_idx',
            old_name='pipeline_jo_job_id_timest_idx',
        ),
        migrations.RenameIndex(
            model_name='jobevent',
            new_name='job_events_event_t_a2411e_idx',
            old_name='pipeline_jo_event_t_timest_idx',
        ),
        migrations.AlterField(
            model_name='job',
            name='phase',
            field=models.CharField(choices=[('seed', 'Seed'), ('resolve', 'Resolve'), ('crawl', 'Crawl'), ('classify', 'Classify'), ('990-enrich', '990 Enrich'), ('990-index', '990 Index'), ('990-parse', '990 Parse'), ('enrich-phone', 'Phone Enrich'), ('extract-context', 'Extract Context'), ('reclassify', 'Reclassify'), ('compare-classify', 'Compare Classify'), ('resolve-disagree', 'Resolve Disagreements'), ('promote-classify', 'Promote Classification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jobevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='hostcommand',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pipelineconfig',
            constraint=models.CheckConstraint(condition=models.Q(('pk', 1)), name='singleton_config'),
        ),
    ]
