# Generated by Django 6.0.4 on 2026-05-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_pipeline_config_and_host_commands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phase',
            field=models.CharField(choices=[('seed', 'Seed'), ('resolve', 'Resolve'), ('crawl', 'Crawl'), ('classify', 'Classify'), ('990-enrich', '990 Enrich'), ('990-index', '990 Index'), ('990-parse', '990 Parse'), ('enrich-phone', 'Phone Enrich'), ('extract-context', 'Extract Context'), ('reclassify', 'Reclassify'), ('compare-classify', 'Compare Classify'), ('resolve-disagree', 'Resolve Disagreements'), ('promote-classify', 'Promote Classification'), ('parse', 'Parse')], max_length=20),
        ),
    ]
